<?xml version="1.0" encoding="utf-8"?><Database Name="AddressBook" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-4L6NSGO\SQLEXPRESS;Initial Catalog=AddressBook;Integrated Security=True" SettingsObjectName="WindowsFormsApplication5.Properties.Settings" SettingsPropertyName="AddressBookConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BizContacts" Member="BizContacts">
    <Type Name="BizContact">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date_Added" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Postal_Code" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(320)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>